"use client";
import {useState} from "react";
export default function AdminLogin(){
 const [username,setUsername]=useState("");const [password,setPassword]=useState("");const [error,setError]=useState("");const [loading,setLoading]=useState(false);
<<<<<<< HEAD
 async function submit(e){e.preventDefault();setError("");setLoading(true);try{const r=await fetch("/api/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username,password})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Login gagal.");const requestedNext=new URLSearchParams(window.location.search).get("next")||"/admin";const next=requestedNext.startsWith("/")&&!requestedNext.startsWith("//")?requestedNext:"/admin";window.location.href=next;}catch(e){setError(e.message);setLoading(false);}}
=======
 async function submit(e){e.preventDefault();setError("");setLoading(true);try{const r=await fetch("/api/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username,password})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Login gagal.");const next=new URLSearchParams(window.location.search).get("next")||"/admin";window.location.href=next;}catch(e){setError(e.message);setLoading(false);}}
>>>>>>> 7945d3e52462ae5b2a03b664ee77d9025c89f585
 return <main className="login-page"><section className="login-card"><div className="eyebrow">16FLAMES · ADMIN</div><h1>LOGIN ADMIN</h1><p>Masuk untuk mengelola pesanan, status pengiriman, dan nomor resi.</p><form onSubmit={submit}><label>USERNAME<input autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} required/></label><label>PASSWORD<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<div className="error">{error}</div>}<button disabled={loading}>{loading?"MEMERIKSA...":"MASUK ADMIN"}</button></form><a href="/">KEMBALI KE TOKO</a></section><style jsx>{`.login-page{min-height:100vh;background:#f5f1ed;display:flex;align-items:center;justify-content:center;padding:20px;font-family:Arial,Helvetica,sans-serif;color:#111}.login-card{width:min(460px,100%);background:#fff;padding:42px;box-shadow:0 20px 70px #0001}.eyebrow{font-size:10px;letter-spacing:3px;font-weight:800;color:#777}.login-card h1{font-size:42px;letter-spacing:-2px;margin:10px 0}.login-card p{color:#666;font-size:13px;line-height:1.7;margin-bottom:28px}form{display:grid;gap:16px}label{display:grid;gap:7px;font-size:9px;font-weight:900;letter-spacing:1.5px}input{width:100%;box-sizing:border-box;border:1px solid #ccc;background:#fff;padding:14px;font-size:14px;letter-spacing:0}button{border:0;background:#111;color:#fff;padding:15px;font-size:10px;font-weight:900;letter-spacing:1px;cursor:pointer}button:disabled{opacity:.6;cursor:wait}.error{background:#f8e7e7;border:1px solid #e2bebe;color:#9b2222;padding:12px;font-size:11px;line-height:1.5}.login-card>a{display:block;text-align:center;margin-top:18px;color:#111;font-size:10px;font-weight:800;letter-spacing:1px;text-decoration:none}@media(max-width:600px){.login-card{padding:27px}.login-card h1{font-size:32px}}`}</style></main>;
}
